title: Tolulope Akinmoju # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 I love to analyze everything data
  <br><br> 
  <br><br>
  <a href="https://https://www.linkedin.com/in/tolulope-akinmoju/">View My LinkedIn Profile</a> 
  <a href="https://https://https://github.com/Tolulope-Akinmoju/">View My Github Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
